expect_error(nih_research(1929))
expect_error(nih_research('aaa'))
expect_s3_class(nih_research(1999), 'data.frame')
expect_equal(nrow(nih_research(2021)), 82122)
expect_s3_class(median_total_cost(data2), c("gg", "ggplot"))
expect_s3_class(funding_frequency(data2), c("plotly", "htmlwidget"))
